### ISSUE TITLE
how to save?

### ISSUE THREAD

**Issue by Researcher33** [Thenlie/password-generator#2]
Hello, how can we collect each generated password in a file as a document.

**Comment by Thenlie** [comment]
Currently there is no ability to save passwords for later reference. This repo could be a great starting point if you wanted to add that functionality yourself. You could also simply copy and paste the results into your favorite password manager or spreadsheet. 

I may look into adding this functionality in the future but right now I do not have time time.

**Comment by Researcher33** [comment]
So can you guide me to do this? I'm pretty new to coding.

**Comment by Thenlie** [comment]
This would be a pretty involved process depending on how you want to implement it. Not something I can work on right now but feel free to clone or fork this and try yourself. 

You can look into the node file system module as that can write to files. This also could be done by creating a backend and storing the results in a database. 

Hope this helps! 

Since this is not really within the scope of this project at the moment I am going to close this issue.
